import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

import { departmentsOrProjects, users } from "./access";
import { auditColumns, softDeleteColumns } from "./_shared";

export const taskTemplates = sqliteTable(
  "task_templates",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").references(() => users.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description"),
    category: text("category"),
    expectedOutput: text("expected_output"),
    linkedProjectId: text("linked_project_id").references(() => departmentsOrProjects.id),
    usageCount: integer("usage_count").notNull().default(0),
    lastUsedAt: text("last_used_at"),
    isShared: integer("is_shared", { mode: "boolean" }).notNull().default(false),
    ...auditColumns(),
    ...softDeleteColumns(),
  },
  (table) => ({
    userIdx: index("task_templates_user_idx").on(table.userId),
  }),
);

export const workPlans = sqliteTable(
  "work_plans",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    month: text("month").notNull(),
    status: text("status").notNull().default("draft"),
    autosavedAt: text("autosaved_at"),
    submittedAt: text("submitted_at"),
    approvedAt: text("approved_at"),
    approvedBy: text("approved_by").references(() => users.id),
    reviewerComment: text("reviewer_comment"),
    ...auditColumns(),
    ...softDeleteColumns(),
  },
  (table) => ({
    userMonthIdx: uniqueIndex("work_plans_user_month_idx").on(table.userId, table.month),
    statusIdx: index("work_plans_status_idx").on(table.status),
  }),
);

export const workPlanItems = sqliteTable(
  "work_plan_items",
  {
    id: text("id").primaryKey(),
    workPlanId: text("work_plan_id")
      .notNull()
      .references(() => workPlans.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    month: text("month").notNull(),
    planDate: text("plan_date").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
    title: text("title").notNull(),
    description: text("description"),
    expectedOutput: text("expected_output"),
    category: text("category"),
    priority: text("priority").notNull().default("medium"),
    linkedProjectId: text("linked_project_id").references(() => departmentsOrProjects.id),
    holidayType: text("holiday_type").notNull().default("none"),
    holidayLabel: text("holiday_label"),
    notes: text("notes"),
    status: text("status").notNull().default("planned"),
    isAutoGenerated: integer("is_auto_generated", { mode: "boolean" })
      .notNull()
      .default(false),
    followUpRequired: integer("follow_up_required", { mode: "boolean" })
      .notNull()
      .default(false),
    ...auditColumns(),
    ...softDeleteColumns(),
  },
  (table) => ({
    userDateIdx: index("work_plan_items_user_date_idx").on(table.userId, table.planDate),
    monthIdx: index("work_plan_items_month_idx").on(table.month),
    statusIdx: index("work_plan_items_status_idx").on(table.status),
  }),
);

export const dailyActivities = sqliteTable(
  "daily_activities",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    activityDate: text("activity_date").notNull(),
    activityTime: text("activity_time").notNull(),
    taskDescription: text("task_description").notNull(),
    output: text("output"),
    note: text("note"),
    delivery: text("delivery"),
    linkedPlanItemId: text("linked_plan_item_id").references(() => workPlanItems.id),
    followUpDate: text("follow_up_date"),
    followUpNote: text("follow_up_note"),
    reminderStatus: text("reminder_status").notNull().default("none"),
    status: text("status").notNull().default("draft"),
    printGroupId: text("print_group_id"),
    submittedAt: text("submitted_at"),
    ...auditColumns(),
    ...softDeleteColumns(),
  },
  (table) => ({
    userDateIdx: index("daily_activities_user_date_idx").on(table.userId, table.activityDate),
    statusIdx: index("daily_activities_status_idx").on(table.status),
    linkedPlanIdx: index("daily_activities_linked_plan_idx").on(table.linkedPlanItemId),
  }),
);

export const followUps = sqliteTable(
  "follow_ups",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    sourceType: text("source_type").notNull(),
    sourceId: text("source_id"),
    title: text("title").notNull(),
    note: text("note"),
    dueDate: text("due_date").notNull(),
    priority: text("priority").notNull().default("medium"),
    status: text("status").notNull().default("pending"),
    reminderSeen: integer("reminder_seen", { mode: "boolean" }).notNull().default(false),
    reminderDismissedAt: text("reminder_dismissed_at"),
    completedAt: text("completed_at"),
    snoozedUntil: text("snoozed_until"),
    assignedToUserId: text("assigned_to_user_id").references(() => users.id),
    ...auditColumns(),
    ...softDeleteColumns(),
  },
  (table) => ({
    userDueIdx: index("follow_ups_user_due_idx").on(table.userId, table.dueDate),
    statusIdx: index("follow_ups_status_idx").on(table.status),
    assignedIdx: index("follow_ups_assigned_idx").on(table.assignedToUserId),
  }),
);

export const holidays = sqliteTable(
  "holidays",
  {
    id: text("id").primaryKey(),
    holidayDate: text("holiday_date").notNull(),
    holidayType: text("holiday_type").notNull().default("govt_holiday"),
    label: text("label").notNull(),
    countryCode: text("country_code").notNull().default("BD"),
    isRecurring: integer("is_recurring", { mode: "boolean" }).notNull().default(false),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    isOverrideAllowed: integer("is_override_allowed", { mode: "boolean" }).notNull().default(true),
    ...auditColumns(),
    ...softDeleteColumns(),
  },
  (table) => ({
    dateIdx: uniqueIndex("holidays_date_idx").on(table.holidayDate),
    activeIdx: index("holidays_active_idx").on(table.isActive),
  }),
);
