import { z } from "zod";

import {
  DAILY_ACTIVITY_STATUSES,
  FOLLOW_UP_STATUSES,
  HOLIDAY_TYPES,
  MONTHLY_REPORT_STATUSES,
  PRIORITY_OPTIONS,
  WORK_PLAN_ITEM_STATUSES,
  WORK_PLAN_STATUSES,
} from "@/lib/constants";
import { isoDateSchema, monthSchema, timeSchema } from "@/lib/validation/shared";

export const workPlanItemSchema = z.object({
  id: z.string().optional(),
  planDate: isoDateSchema,
  title: z.string().min(3).max(220),
  description: z.string().max(1000).optional().nullable(),
  expectedOutput: z.string().max(500).optional().nullable(),
  category: z.string().max(120).optional().nullable(),
  priority: z.enum(PRIORITY_OPTIONS).default("medium"),
  linkedProjectId: z.string().optional().nullable(),
  holidayType: z.enum(HOLIDAY_TYPES).default("none"),
  holidayLabel: z.string().max(120).optional().nullable(),
  notes: z.string().max(500).optional().nullable(),
  status: z.enum(WORK_PLAN_ITEM_STATUSES).default("planned"),
  followUpRequired: z.boolean().default(false),
  isAutoGenerated: z.boolean().default(false),
  sortOrder: z.number().int().nonnegative().default(0),
});

export const workPlanSchema = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  month: monthSchema,
  status: z.enum(WORK_PLAN_STATUSES).default("draft"),
  reviewerComment: z.string().max(500).optional().nullable(),
  items: z.array(workPlanItemSchema).min(1),
});

export const workPlanGenerateSchema = z.object({
  month: monthSchema,
  userId: z.string().optional(),
  duplicatePreviousMonth: z.boolean().default(false),
  carryForwardUnfinished: z.boolean().default(true),
});

export const dailyActivitySchema = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  activityDate: isoDateSchema,
  activityTime: timeSchema,
  taskDescription: z.string().min(3).max(500),
  output: z.string().max(500).optional().nullable(),
  note: z.string().max(700).optional().nullable(),
  delivery: z.string().max(500).optional().nullable(),
  linkedPlanItemId: z.string().optional().nullable(),
  followUpDate: isoDateSchema.optional().nullable(),
  followUpNote: z.string().max(500).optional().nullable(),
  reminderStatus: z.string().default("none"),
  status: z.enum(DAILY_ACTIVITY_STATUSES).default("draft"),
  printGroupId: z.string().optional().nullable(),
});

export const followUpSchema = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  sourceType: z.enum(["activity", "work_plan", "manual"]),
  sourceId: z.string().optional().nullable(),
  title: z.string().min(3).max(200),
  note: z.string().max(500).optional().nullable(),
  dueDate: isoDateSchema,
  priority: z.enum(PRIORITY_OPTIONS).default("medium"),
  status: z.enum(FOLLOW_UP_STATUSES).default("pending"),
  snoozedUntil: isoDateSchema.optional().nullable(),
  assignedToUserId: z.string().optional().nullable(),
});

export const monthlyReportCompletedItemSchema = z.object({
  id: z.string().optional(),
  taskDate: isoDateSchema.optional().nullable(),
  taskName: z.string().min(3).max(220),
  output: z.string().max(500).optional().nullable(),
  remarks: z.string().max(300).optional().nullable(),
  sourceActivityId: z.string().optional().nullable(),
  sortOrder: z.number().int().nonnegative().default(0),
});

export const monthlyReportOngoingItemSchema = z.object({
  id: z.string().optional(),
  taskName: z.string().min(3).max(220),
  output: z.string().max(500).optional().nullable(),
  deadline: isoDateSchema.optional().nullable(),
  remarks: z.string().max(300).optional().nullable(),
  sourceFollowUpId: z.string().optional().nullable(),
  sortOrder: z.number().int().nonnegative().default(0),
});

export const monthlyReportNextMonthItemSchema = z.object({
  id: z.string().optional(),
  taskName: z.string().min(3).max(220),
  taskDate: isoDateSchema.optional().nullable(),
  output: z.string().max(500).optional().nullable(),
  remarks: z.string().max(300).optional().nullable(),
  sourcePlanItemId: z.string().optional().nullable(),
  sortOrder: z.number().int().nonnegative().default(0),
});

export const monthlyReportSchema = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  month: monthSchema,
  projectName: z.string().max(220).optional().nullable(),
  reportName: z.string().max(220).optional().nullable(),
  designationSnapshot: z.string().max(120).optional().nullable(),
  submissionDate: isoDateSchema.optional().nullable(),
  status: z.enum(MONTHLY_REPORT_STATUSES).default("draft"),
  lessonsLearned: z.string().max(1000).optional().nullable(),
  comments: z.string().max(1000).optional().nullable(),
  adminComment: z.string().max(1000).optional().nullable(),
  submittedByName: z.string().max(120).optional().nullable(),
  approvedByName: z.string().max(120).optional().nullable(),
  completedItems: z.array(monthlyReportCompletedItemSchema),
  ongoingItems: z.array(monthlyReportOngoingItemSchema),
  nextMonthItems: z.array(monthlyReportNextMonthItemSchema),
});

export const activityFilterSchema = z.object({
  fromDate: isoDateSchema.optional(),
  toDate: isoDateSchema.optional(),
  query: z.string().optional(),
  status: z.string().optional(),
});

export type WorkPlanItemInput = z.infer<typeof workPlanItemSchema>;
export type WorkPlanInput = z.infer<typeof workPlanSchema>;
export type DailyActivityInput = z.infer<typeof dailyActivitySchema>;
export type FollowUpInput = z.infer<typeof followUpSchema>;
export type MonthlyReportInput = z.infer<typeof monthlyReportSchema>;
